### ISSUE TITLE
upperbound is not being used

### ISSUE THREAD

**Issue by kykungz** [OOP2018/guessing-game-poom201211#1]
`upperbound` is not being used when generating the `secret`
https://github.com/OOP2018/guessing-game-poom201211/blob/a9212f7a4f36a1b5e65dd2e85fda03b74eef96e0/src/PoomGuessingGame.java#L18-L22

**Comment by kykungz** [comment]
Reopen this issue because upperbound is still not being used when generating secret.
https://github.com/OOP2018/guessing-game-poom201211/blob/a9212f7a4f36a1b5e65dd2e85fda03b74eef96e0/src/PoomGuessingGame.java#L18-L22
```
// this only generate secret number from 1 - 100, not 1 - upperbound.
this.secret = secretNum.nextInt(100) + 1; 
```
If you have fixed this issue, please make sure you've committed and push the code.
After that, feel free to close this issue.

**Comment by poom201211** [comment]
sorry i accidentally closed it

**Comment by poom201211** [comment]
Is it okay now?

**Comment by kykungz** [comment]
Yes! 💯
